### ISSUE TITLE
Support for container or `Eigen::Map`

### ISSUE THREAD

**Issue by mlund** [DavidAce/h5pp#1]
I am testing your nice library in a code for storing particle data as a function of time. I use STL containers of structs to store data and as such the properties are non-contiguous. For convenience I often use `Eigen::Map` to create views into a container, for example:

~~~ cpp
    /**
     * @brief Eigen::Map facade to data members in STL container
     *
     * Example:
     *    struct Particle { Eigen::Vector3d pos; double charge; };
     *    std::vector<Particle> v(10);
     *    auto m1 = asEigenMatrix(v.begin, v.end(), &Particle::pos);    --> 10x3 view
     *    auto m2 = asEigenVector(v.begin, v.end(), &Particle::charge); --> 10x1 view
     */
    template<typename dbl=double, class iter, class memberptr>
        auto asEigenMatrix(iter begin, iter end, memberptr m) {
            typedef typename std::iterator_traits<iter>::value_type T;
            static_assert( sizeof(T) % sizeof(dbl) == 0, "value_type size must multiples of double");
            const size_t s = sizeof(T) / sizeof(dbl);
            const size_t cols = sizeof(((T *) 0)->*m) / sizeof(dbl);
            typedef Eigen::Matrix<dbl, Eigen::Dynamic, cols> Tmatrix;
            return Eigen::Map<Tmatrix, 0, Eigen::Stride<1,s>>((dbl*)&(*begin.*m), end-begin, cols).array();
        }

    template<typename dbl=double, class iter, class memberptr>
        auto asEigenVector(iter begin, iter end, memberptr m) {
            typedef typename std::iterator_traits<iter>::value_type T;
            static_assert( std::is_same<dbl&, decltype(((T *) 0)->*m)>::value, "member must be a scalar");
            return asEigenMatrix<dbl>(begin, end, m).col(0);
        }
~~~

Interestingly, `writeDataset(m2, "charges")` compiles, but the output is wrong as the stride, I suspect, is ignored. Is this something that could be implemented? Support for containers or ranges would of course be equally useful.

**Update:** I tried the above but with `m1` (i.e. `pos` instead of `charge`) and I get the correct h5 output:
~~~ bash
$ h5dump traj.h5 
HDF5 "traj.h5" {
GROUP "/" {
   DATASET "coordinates" {
      DATATYPE  H5T_IEEE_F64LE
      DATASPACE  SIMPLE { ( 40, 3 ) / ( 40, 3 ) }
      DATA {
      (0,0): 14.8964, -6.9353, -14.4038,
      (1,0): -3.89562, -16.3067, -9.90434,
      (2,0): -14.4895, -22.4392, -23.1779,
      (3,0): 21.0437, 15.3766, 10.2887,
      ...
~~~

My final aim is to add one more dimension representing the frame number as the particle positions are saved at different steps. The HDF5 reference for this is shown below for 10 frames and 6000 particles. Any suggestions for achieving this would be very helpful! I would need to write and read each of the 10 frames individually.
~~~
   DATASET "coordinates" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SIMPLE { ( 10, 6000, 3 ) / ( H5S_UNLIMITED, 6000, 3 ) }
      DATA {
      (0,0,0): 2.66322, 1.55546, 3.92376,
      (0,1,0): 2.68008, 1.59389, 3.833,
      (0,2,0): 2.61028, 1.62054, 3.9782,
      (0,3,0): 3.79721, 0.870623, 2.46164,
      (0,4,0): 3.70177, 0.883923, 2.48837,
      ...
      (1,0,0): ....
~~~

**Comment by DavidAce** [comment]
I'm happy to take a look.

Currently h5pp supports contiguous containers such as std::array, c-style arrays, std::vectors or Eigen (or Eigen::Map!) with POD data. As far as I can tell, there is no way to tell HDF5 to write a non-contiguous block of data (i.e. to specify a stride), but I'm still learning. I have decided not to support ranges because not all STL containers are contiguous, like std::list. I think offering the possibility would send mixed messages: I would either have to copy the list data to a contiguous vector, or write elements one by one to individual datasets, but these are decisions a user should make instead. So I decided to simply check if the container has a ".data()" method - contiguous containers usually do.

However, going back to your problem, it is possible to write entire POD structs, or STL containers thereof. It's just a matter of registering and defining a compound HDF5 type  before writing it. In fact, I do this at initialization to enable support for `std::complex`, and CUDA structs like `struct double2{double x,y;}`. Code is found in `include/h5pp/details/h5ppTypeCompoundCreate.h`


So for instance, a struct like,

```c++
struct Particle {
    double x,y,z,t;
    int dim;
    
}
```
is registered in HDF5 with

```c++
        // hid_t can be replaced by a safer h5pp::hid::h5t below,
        hid_t MY_HDF5_PARTICLE_TYPE = H5Tcreate(H5T_COMPOUND, sizeof(Particle));
        H5Tinsert(MY_HDF5_PARTICLE_TYPE, "x", HOFFSET(Particle, x), H5T_NATIVE_DOUBLE);
        H5Tinsert(MY_HDF5_PARTICLE_TYPE, "y", HOFFSET(Particle, y), H5T_NATIVE_DOUBLE);
        H5Tinsert(MY_HDF5_PARTICLE_TYPE, "z", HOFFSET(Particle, z), H5T_NATIVE_DOUBLE);
        H5Tinsert(MY_HDF5_PARTICLE_TYPE, "t", HOFFSET(Particle, t), H5T_NATIVE_DOUBLE);
        H5Tinsert(MY_HDF5_PARTICLE_TYPE, "dim", HOFFSET(Particle, dim), H5T_NATIVE_INT);
    
```

If you'd find this useful I can look into a way of letting users register their own structs and pass them to h5pp in some way. I'm thinking something along the lines of

```c++
std::vector<Particle> particles(10);
...
//register as above
...

myfile.writeDataset(particles, MY_HDF5_PARTICLE_TYPE,"particles");

```

Another option is to use HDF5 Tables which is specifically geared at time-series data in low-latency settings. h5pp doesn't currently support this, because the entries in the time-series have to be registered in the same way.

**Comment by mlund** [comment]
Thanks for looking into this. I still do not understand why the `m1` approach above works as Map should use a stride to access the POD for the positions, only?

**Comment by DavidAce** [comment]
I think I've found the reason. When writing Eigen types, these are automatically transformed to row-major (as wanted by HDF5) by coyping into a temporary object. In the case of Eigen::Map, the temporary object is actually a row-major instance of the wrapped type.
This "copy" probably just does the correct thing and honor's the stride.

**Comment by DavidAce** [comment]
In any case, I have implemented the user-defined types as I mentioned yesterday. It turns out that I need this feature for my own project. More specifically I need to make tables of user-defined HDF5 compound types, so now I have implemented that too. Check out the new examples 5 and 6 in the wiki. I believe HDF5 tables could be a cleaner solution for time-series data.

**Comment by DavidAce** [comment]
I have decided to close this issue for now. The library has support for Eigen::Map and Eigen::TensorMap, and I have added support for user-defined POD structs. However, non-contiguous containers and non-POD structs with dynamic data seems much harder. Honestly I don't know at how to implement that or if it is even possible. It would be a nice feature though, so pointing me to an implementation or a pull-request is appreciated.
