### ISSUE TITLE
h5pp compatibility issues with hdf5 1.13

### ISSUE THREAD

**Issue by OlafHartwig** [DavidAce/h5pp#11]
Hi! Thank you very much for writing this very nice library, it is very useful!

We have been experimenting with using it in one of our projects, and it is working perfectly for the most part. However, we noticed a compatibility issue with the latest versions of the hdf5 c++ library. In detail, the following error message is produced when building the project:

```
/h5pp/details/h5ppPropertyLists.h:13:32: error: no viable conversion from 'int' to 'hid::h5p'
        hid::h5p fileCreate  = H5P_DEFAULT; // H5Pcreate(H5P_FILE_CREATE);
```

We tested this with hdf5 versions 1.10.8 and 1.13.0. The error does not occur on other versions of hdf5 we tested, which are 1.10.7_1 and 1.12.1.

I checked on [the official homepage](https://portal.hdfgroup.org/display/support/HDF5%201.13.0#knownprob), and this seems to be a known incompatibility between hdf5 1.12 and 1.13:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/60234310/159680073-35c7efb2-ef51-443b-8495-f677ce4414de.png">

I'm not sure why it also seemed to have been changed between 1.10.7_1 and 1.10.8.

Before we look further into this we wanted to reach out as you might have a better idea of what exactly is happening here, and maybe even already have a fix?

**Comment by DavidAce** [comment]
Hi! Thank you for bringing this to my attention. I have not yet had time to update or test h5pp with HDF5 1.13, so unfortunately I have no fix yet. I was planning on waiting for 1.13 to become available on [conan](https://conan.io/center/hdf5) first, but I don't know how long that will take.

Just from the changelog description though, I believe the issue is that `hid_t` is an alias for `int64_t`, and now in HDF5 1.13 that we get H5P_DEFAULT is just a plain `0` interpreted as an `int`. The class h5pp::hid::h5p has a constructor for `hid_t` but not for `int`, which is why the line fails. The simplest solution would be to cast H5P_DEFAULT to `hid_t`, like

```c++
hid::h5p fileCreate  = static_cast<hid_t>(H5P_DEFAULT);
```
and similarly for the other members. One could also consider adding an `int` constructor for the base class of `hid::h5p` but that could potentially cause other issues. 
I'm a bit short on time at least until ~summer so I would greatly appreciate if you can try this since you already have HDF5 1.13 set up. If it works I can make the change or accept a pull request.

**Comment by DavidAce** [comment]
I managed to install HDF5 1.13.1 and my tests pass after the extending the constructor of `hid` from `hid_t` to all integral types. The patch is in `a8471cd` on the master branch. I hope this fixes the issue on your end!

**Comment by OlafHartwig** [comment]
Thanks for the quick reply, and the elegant solution! 

I tested it in our project, and it indeed resolved the issue. It now runs without issue on both hdf5 1.12.1 and 1.13.0.

Thanks again!
