### ISSUE TITLE
Compilation Failure on M1 MacOS due to Missing -lrt and -lsz

### ISSUE THREAD

**Issue by yonghuier** [DavidAce/h5pp#19]
**Issue Description:**
I'm encountering compilation issues on M1 MacOS with the Homebrew clang version 16.0.6 and architecture arm64-apple-darwin22.5.0. Specifically, I'm facing two problems:

1. **Missing -lsz:** When I use CMake to build the project, it reports that it cannot find -lsz. I have tried to address this by using `-DCMAKE_PROJECT_TOP_LEVEL_INCLUDES` to install dependencies. While this works for building the h5pp library successfully, it fails during the linking phase when integrating it into my project.

2. **Missing -lrt:** Interestingly, when I disable tests, I can successfully build the h5pp library. However, when I attempt to link it to my project, it fails again, this time indicating that it cannot find -lrt. 

I'm seeking guidance on how to resolve these issues. Any help in resolving the missing -lsz and -lrt problems on my M1 MacOS system with the provided compiler and architecture would be greatly appreciated.

**Comment by DavidAce** [comment]
As far as I can tell, these two libraries are included by the underlying HDF5 library.

Since h5pp is a header-only library, compilation only happens when building the tests, as you have noticed. 

You have a couple of options around this. The first thing you can try is to play with the CMake flag "-DH5PP_PACKAGE_MANAGER=<find|cmake|conan>". The default is "find", which uses the find_package mechanism to find the dependencies in your system. It should work if you have installed dependencies from brew: `brew install hdf5 spdlog fmt eigen` . Note that h5pp 1.11.0 does not yet have support for the latest fmt version 1.10 and up.

**Comment by DavidAce** [comment]
As far as I can tell, these two libraries are included by the underlying HDF5 library. -lsz is for the szip library and -lrt is the real-time extensions library. For the szip library, you can check if it is installed in in your system (e.g. with brew). 

Since h5pp is a header-only library, compilation only happens when building the tests, as you have noticed. However, I have included opt-in flags to let h5pp build its dependencies on the fly, using a "CMake-only" approach or using the conan package manager.

The easiest way to let h5pp install dependencies automatically is by using the presets provided. To list the presets run `cmake --list-presets` in the root directory. You can inherit and build upon any of those presets with [`CMakeUserPresets.json`](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html). See also the following github action running on macos12 where these approaches work:  https://github.com/DavidAce/h5pp/actions/runs/6059557138/workflow

If none of this is working, try pasting the output from your CMake configure, after adding for instance `--log-level=verbose` or passing `-DCMAKE_MESSAGE_LOG_LEVEL=VERBOSE`. This should print what each CMake target is linking to.

**Comment by DavidAce** [comment]
I'm closing this for now, but feel free to create a new issue if the problem persists in the newest release of h5pp.
