### ISSUE TITLE
h5pp without CMake (HDF5 windows binary installer)

### ISSUE THREAD

**Issue by izsahara** [DavidAce/h5pp#7]
As a complete beginner my setup is a simple one, that is (On a Windows machine) using Visual Studio 2019 (without any use/familiarity with CMake). So building/including directories and all that stuff occurs within VS. 

- Simply including the directory 'h5pp/include' and building my project would not work as it depends on HDF5.
- So I simply downloaded the binary (https://portal.hdfgroup.org/display/support/HDF5+1.8.22#files) and installed HDF5.
- Now I have a bunch of .lib and header files from HDF5. 
- So i added the include file and libs directory from HDF5 to my VS Project

Which libs, from HDF5, should I add into the linker args?
If there is a much easier option (Without CMake) that would allow me to simply build from VS would be very much appreciated.

Thanks

**Comment by DavidAce** [comment]
First thing, if you are just starting out with HDF5 you may as well go for [version 1.12.1](https://portal.hdfgroup.org/display/support/HDF5+1.12.1). 

After installing HDF5, you need to tell VS to:
* link the HDF5 "C" and "HL" libraries to your executable, which should be called something like `libhdf5.lib` and `libhdf5_hl.lib`, respectively. Order is important if you are doing static linking, and the C library goes last.
* link the zlib and szip/aec which should be included according to the README that comes with the HDF5 binary. These should be called zlib.lib and libszip.lib (and/or libaec.lib) or similar.
* include the HDF5 header directory
* set compiler flags as [explained here](https://github.com/DavidAce/h5pp/issues/6#issuecomment-921715038)

I think after this the you should be able to build a minimal HDF5 application, and the h5pp headers should work fine.

Managing link dependencies for C++ projects manually is a bit of a mess, honestly. It's a good learning exercise, but if you want to save yourself some time and headaches, you should use a package manager to handle dependencies and a build system such as CMake, Meson or VS itself to integrate those dependencies to your project. [VS2019 has native support for CMake](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160) projects. For package manager I recommend [conan](https://conan.io/) or [vcpkg](https://vcpkg.io), both of which can install HDF5, spdlog, fmt and Eigen3 (and any depedendencies that they could need, recursively) in essentially oneliners. Granted, conan and vcpkg will use CMake under the hood, but you don't need to know anything about CMake other than installing it on your system. There is also a [VS2019 extension for conan]https://blog.conan.io/2019/06/17/Conan-extension-for-Visual-Studio.html).

I have added [h5pp to the conan center index](https://conan.io/center/h5pp) and I would say this is probably the simplest way of getting started, since it will install h5pp and its dependencies recursively. Under [`quickstart`](https://github.com/DavidAce/h5pp/tree/master/quickstart) there are 3 different examples for how one could use conan to get started: [[1]](https://github.com/DavidAce/h5pp/tree/master/quickstart/git-clone-cmake-conan-integration), [[2]](https://github.com/DavidAce/h5pp/tree/master/quickstart/git-clone-conan-generator-cmake) and [[3]](https://github.com/DavidAce/h5pp/tree/master/quickstart/git-clone-install-with-conanfile.py). The shell scripts in there are for linux shells but they cover the gist of it and will point you in the right direction.
